# Generated by Django 2.1 on 2019-08-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumerapp', '0002_auto_20190802_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcon',
            name='country',
            field=models.CharField(default='Pitcairn Islands', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentcon',
            name='dob',
            field=models.DateField(default='2004-06-26'),
        ),
        migrations.AlterField(
            model_name='studentcon',
            name='first_name',
            field=models.CharField(default='Steven', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentcon',
            name='last_name',
            field=models.CharField(default='Walker', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentcon',
            name='password',
            field=models.CharField(default='None', max_length=55),
        ),
        migrations.AlterField(
            model_name='studentcon',
            name='phone_nu',
            field=models.CharField(default='8600724200', max_length=50),
        ),
    ]
